[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xfd\xff\xff\xff\xe2\0\0\x2\x94\0\0\x1\x9d\0\0\0\0\0\0\0\0\0\0\x2\x91\0\0\x1\x9a\0\0\0\0\0\0\0\0\x6\xa8\0\0\0\0\0\0\0\0\0\0\x2\x91\0\0\x1\x9a)

[Settings]
alwaysShowInTray=false
checkRcloneBrowserUpdates=true
checkRcloneUpdates=true
closeToTray=false
darkMode=false
darkModeIni=false
defaultDownloadDir=
defaultDownloadOptions=
defaultRcloneOptions=--fast-list
defaultUploadDir=
defaultUploadOptions=
http_proxy=
https_proxy=
iconSize=medium
lastRcloneBrowserUpdateCheck=Thu Jul 18 2024
lastRcloneUpdateCheck=Thu Jul 18 2024
lastUsedDestFolder=
lastUsedSourceFolder=
mount=--vfs-cache-mode full
no_proxy=
notifyFinishedTransfers=true
rclone=/usr/bin/rclone
rcloneConf=
rcloneVersion=1.67.0
rowColors=true
showFileIcons=true
showFolderIcons=true
showHidden=true
stream=
useProxy=false
