### TUNING NETWORK PERFORMANCE ###
# Tolga Erok
#        
# net.core.default_qdisc = fq_codel                                                  # Set the default queuing discipline (qdisc) for the kernel's network scheduler to "cake"
net.core.rmem_max = 1073741824                                          # Set the maximum socket receive buffer size for all network devices to 1073741824 bytes
net.core.wmem_max = 1073741824                                        # Set the maximum socket send buffer size for all network devices to 1073741824 bytes
net.ipv4.tcp_congestion_control = westwood                        # Set the TCP congestion control algorithm to "westwood"
net.ipv4.tcp_mem = 65536 1048576 16777216                      # Set TCP memory allocation limits
net.ipv4.tcp_mtu_probing = 1                                                    # Enable Path MTU Discovery
net.ipv4.tcp_notsent_lowat = 16384                                         # Minimum amount of data in the send queue below which TCP will send more data
net.ipv4.tcp_retries2 = 8                                                             # Set the number of times TCP retransmits unacknowledged data segments for the second SYN on a connection initiation to 8
net.ipv4.tcp_rmem = 4096 87380 1073741824                      # Set TCP read memory allocation for network sockets
net.ipv4.tcp_rmem = 8192 1048576 16777216                      # TCP read memory allocation for network sockets
net.ipv4.tcp_sack = 1                                                                   # Enable Selective Acknowledgment (SACK)
net.ipv4.tcp_slow_start_after_idle = 0                                      # Disable TCP slow start after idle
net.ipv4.tcp_tw_reuse = 1                                                           # Increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
net.ipv4.tcp_window_scaling = 1                                               # Enable TCP window scaling
net.ipv4.tcp_wmem = 4096 87380 1073741824                     # Set TCP write memory allocation for network sockets
net.ipv4.tcp_wmem = 8192 1048576 16777216                     # TCP write memory allocation for network sockets
net.ipv4.udp_mem = 65536 1048576 16777216                    # Set UDP memory allocation limits
net.ipv4.udp_rmem_min = 16384                                             # Increase the read-buffer space allocatable for UDP
net.ipv4.udp_wmem_min = 16384                                           # Increase the write-buffer-space allocatable for UDP
