
kernel.core_uses_pid = 1               # Append the PID to the core filename
kernel.nmi_watchdog = 0                # Disable NMI watchdog
kernel.panic = 5                       # Reboot after 5 seconds on kernel panic. Default: 0
kernel.pid_max = 4194304               # Allows a large number of processes and threads to be managed. Default: 32768, Tweaked: 4194304
kernel.pty.max = 24000                 # Maximum number of pseudo-terminals (PTYs) in the system
kernel.sched_autogroup_enabled = 0     # Disable automatic task grouping for better server performance
kernel.sysrq = 1                       # Enable SysRQ for rebooting the machine properly if it freezes. [Source](https://oglo.dev/tutorials/sysrq/index.html)
kernel.unprivileged_bpf_disabled = 1   # Disable unprivileged BPF
net.core.default_qdisc = fq_codel
net.core.netdev_max_backlog = 32768    # Maximum length of the input queue of a network device
net.core.optmem_max = 65536            # Maximum ancillary buffer size allowed per socket
net.core.rmem_default = 1048576        # Default socket receive buffer size
net.core.rmem_max = 16777216           # Maximum socket receive buffer size
net.core.somaxconn = 65536             # Maximum listen queue backlog
net.core.wmem_default = 1048576        # Default socket send buffer size
net.core.wmem_max = 16777216           # Maximum socket send buffer size

