
#--------------------------------------------------------------------------------------------------------------------------------------
# Virtual Memory Management
#--------------------------------------------------------------------------------------------------------------------------------------

vm.dirty_background_bytes = 474217728   # Set dirty background bytes for optimized performance (adjusted for SSD).
vm.dirty_background_ratio = 5           # Percentage of system memory at which background writeback starts
vm.dirty_bytes = 742653184              # Set dirty bytes for optimized performance (adjusted for SSD).
vm.dirty_expire_centisecs = 3000        # Set the time at which dirty data is old enough to be eligible for writeout (6000 centiseconds). Adjusted for SSD.
vm.dirty_ratio = 80                     # Set the ratio of dirty memory at which a process is forced to write out dirty data (10%). Adjusted for SSD.
vm.dirty_writeback_centisecs = 300      # Set the interval between two consecutive background writeback passes (500 centiseconds).
vm.extfrag_threshold = 100              # Fragmentation threshold for the kernel
vm.max_map_count=2147483642             # Define the maximum number of memory map areas a process may have
vm.min_free_kbytes = 65536              # Minimum free kilobytes
vm.mmap_min_addr = 65536                # Minimum address allowed for a user-space mmap
vm.page-cluster = 0                     # Disable page clustering for filesystems
vm.swappiness = 1                       # Swappiness parameter (tendency to swap out unused pages)
vm.vfs_cache_pressure = 50              # Controls the tendency of the kernel to reclaim memory used for caching of directory and inode objects
fs.file-max = 67108864                  # Maximum number of file handles the kernel can allocate (Default: 67108864)
fs.aio-max-nr = 1048576                 # Defines the max number of asynchronous I/O requests that can be in progress at a given time.
